apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: saitest
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.7.27
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: postgres
      password: mysecretpassword
      database: mydatabase
    persistence:
      enabled: true
      size: 10Gi
    # Add other PostgreSQL chart values as needed
